[Writable]
  LogLevel = "INFO"

[Service]
  BootTimeout = 30000
  CheckInterval = "10s"
  Host = "localhost"
  ServerBindAddr = ""
  Port = 49990
  Protocol = "http"
  StartupMsg = "device simple started"
  Timeout = 20000
  ConnectRetries = 20
  Labels = []
  EnableAsyncReadings = true
  AsyncBufferSize = 16

[Registry]
  Host = "localhost"
  Port = 8500
  Type = "consul"

[Clients]
  [Clients.Data]
    Protocol = "http"
    Host = "localhost"
    Port = 48080
  [Clients.Metadata]
    Protocol = "http"
    Host = "localhost"
    Port = 48081
  [Clients.Logging]
    Protocol = "http"
    Host = "localhost"
    Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"
  UpdateLastConnected = false
  [Device.Discovery]
    Enabled = false
    Interval = "30s"

[Logging]
  EnableRemote = false
  File = ""

[[DeviceList]]
  Name = "Device888"
  Profile = "Simple-Device"
  Description = "Example of Simple Device"
  Labels = ["industrial"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "simple01"
      Port = "300"
